#C:\Users\martut\microservice-wallet-spring\service-registry\src\main\resources\application.properties
spring.application.name=service-registry
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false