spring.application.name=api-gateway
server.port=8080

# Eureka Server Adresi
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# GATEWAY ROUTING (Yönlendirme)
# User Service Rotaları
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

# Wallet Service Rotaları
spring.cloud.gateway.routes[1].id=wallet-service
spring.cloud.gateway.routes[1].uri=lb://wallet-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/account/**