#C:\Users\martut\microservice-wallet-spring\api-gateway\src\main\resources\application.properties
spring.application.name=api-gateway
server.port=8080

# Eureka Server Adresi
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}

# GATEWAY ROUTING (Yönlendirme)
# User Service Rotaları
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

# Wallet Service Rotaları
spring.cloud.gateway.routes[1].id=wallet-service
spring.cloud.gateway.routes[1].uri=lb://wallet-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/account/**

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG